### ISSUE TITLE
Use placeholder API key

### ISSUE THREAD

**Issue by bukinoshita** [victorexpounder/Backend-API-YUMZ#1]
I don't know if this API key is still valid or not, but it would be good to not expose real API keys and use a placeholder one or add behind an environment variable.

If it's a valid API key, I'd also recommend going into resend and rotate that API key.

https://github.com/victorexpounder/Backend-API-YUMZ/blob/edcf5cea4bb2bc8a653530a18fd4aa19969ca840/controllers/User.js#L156

**Comment by victorexpounder** [comment]
I totally forgot to use an environment variable there, but it has been sorted now thanks.
